# Generated by Django 4.2 on 2026-06-03 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_created_at_alter_project_updated_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectMembership',
        ),
    ]
