# Generated by Django 4.2 on 2026-05-25 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('divisions', '0001_initial'),
        ('tasks', '0006_alter_task_directions_alter_task_teams'),
        ('projects', '0003_invitation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='members',
        ),
        migrations.RemoveField(
            model_name='team',
            name='project',
        ),
        migrations.AlterField(
            model_name='projectmembership',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='divisions.team'),
        ),
        migrations.DeleteModel(
            name='Direction',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
