# Generated by Django 4.2 on 2026-06-07 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_delete_projectmembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='role',
            field=models.CharField(choices=[('owner', 'Владелец'), ('admin', 'Администратор'), ('manager', 'Менеджер'), ('tech_support', 'Техподдержка'), ('hr_analyst', 'Кадровый аналитик'), ('participant', 'Участник')], default='participant', max_length=32),
        ),
    ]
