# Generated by Django 5.1.15 on 2026-06-13 05:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_project_name_alter_project_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='role',
            field=models.CharField(choices=[('owner', 'Владелец'), ('admin', 'Администратор'), ('manager', 'Менеджер'), ('hr_analyst', 'Кадровый аналитик'), ('tech_support', 'Техподдержка'), ('participant', 'Участник')], default='participant', max_length=32),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(300, message='Описание проекта не должно превышать 300 символов.')]),
        ),
    ]
