services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile.prod
    volumes:
      - static_volume:/app/staticfiles
    env_file:
      - .env.prod
    depends_on:
      db:
        condition: service_healthy
    networks:
      - assignia-network

  db:
    image: postgres:15
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 2s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - assignia-network

  nginx:
      image: nginx:latest
      ports:
        - "80:80"
        - "443:443"
      volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        - ./nginx/certs:/etc/nginx/certs:ro
        - static_volume:/app/staticfiles:ro
      depends_on:
        - web
      networks:
        - assignia-network

volumes:
  postgres_data:
  static_volume:

networks:
  assignia-network:
    driver: bridge