# Generated by Django 4.2 on 2026-06-08 18:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_directions', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direction',
            name='description',
            field=models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(64, message='Описание не должно превышать 64 символа.')]),
        ),
    ]
