# Generated by Django 4.2 on 2026-06-01 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project_directions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('is_deleted', models.BooleanField(default=False)),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='project_directions.direction')),
            ],
            options={
                'default_related_name': 'teams',
            },
        ),
    ]
