# Generated by Django 5.1.15 on 2026-06-09 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_teams', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'default_related_name': 'teams', 'ordering': ['-created_at']},
        ),
    ]
