# Generated by Django 4.2 on 2026-06-06 15:11

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('project_tasks', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='task',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
