# Generated by Django 5.1.15 on 2026-06-13 05:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_tasks', '0004_alter_task_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(1000, message='Описание задачи не должно превышать 1000 символов.')]),
        ),
    ]
