# Generated by Django 4.2 on 2026-05-21 08:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='Только буквы, цифры, дефис и подчёркивание.', max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Имя пользователя может содержать только буквы, цифры, дефис и подчёркивание.', regex='^[\\w\\-]+$')], verbose_name='username'),
        ),
    ]
