# Generated by Django 4.2 on 2026-05-22 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_requestmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
