# Generated by Django 4.2 on 2026-05-24 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0003_invitation'),
        ('tasks', '0004_delete_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='assignee',
        ),
        migrations.RemoveField(
            model_name='task',
            name='direction',
        ),
        migrations.RemoveField(
            model_name='task',
            name='team',
        ),
        migrations.AddField(
            model_name='task',
            name='directions',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='projects.direction'),
        ),
        migrations.AddField(
            model_name='task',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='projects.team'),
        ),
        migrations.AlterField(
            model_name='task',
            name='risk_chance',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1),
        ),
        migrations.AlterField(
            model_name='task',
            name='risk_impact',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1),
        ),
        migrations.CreateModel(
            name='TaskAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='tasks.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('task', 'user')},
            },
        ),
    ]
