# Generated by Django 4.2 on 2026-05-25 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divisions', '0001_initial'),
        ('tasks', '0005_remove_task_assignee_remove_task_direction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='directions',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='divisions.direction'),
        ),
        migrations.AlterField(
            model_name='task',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='divisions.team'),
        ),
    ]
