# Generated by Django 4.2 on 2026-05-26 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_task_directions_alter_task_teams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'На рассмотрении'), ('reviewed', 'Рассмотрен'), ('declined', 'Отклонён'), ('converted', 'Преобразован в задачу')], default='pending', max_length=20),
        ),
    ]
