# Generated by Django 5.1.15 on 2026-06-13 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmembership',
            name='role',
            field=models.CharField(choices=[('owner', 'Владелец'), ('admin', 'Администратор'), ('manager', 'Менеджер'), ('hr_analyst', 'Кадровый аналитик'), ('tech_support', 'Техподдержка'), ('participant', 'Участник')], default='participant', max_length=32),
        ),
    ]
